cg_damping: 0.1
cg_iters: 10
entcoeff: 0.0
gamma: 0.99
lam: 0.99
max_episodes: 1.0e+4
max_kl: 0.05
obs_type: pose_only
policy: {gaussian_fixed_var: false, hidden_layers: 2, hidden_size: 128}
reward_type: precision_only
timesteps_per_batch: [8192, 16384, 32768]
vf_iters: 10
vf_stepsize: 1.0e-05
